### ISSUE TITLE
Remove underline in "Go to comparison" button

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-compare-products#13]
Simple CSS issue. Doesn't look good with the text-underline.

**Comment by d4mation** [comment]
This may be a per-theme issue. It doesn't seem to be anywhere within the codebase&mdash;or at least not anymore.

Pictured is Digital Store:

![image](https://cloud.githubusercontent.com/assets/7770631/16465107/1c60e92c-3e0b-11e6-99b9-930a0c7540a0.png)

**Comment by d4mation** [comment]
Actually, I seem to be looking in the wrong spot and there's a JavaScript error associated with it.

Looking into this more.

**Comment by d4mation** [comment]
It turns out the JavaScript was set to only load on Comparison Pages, which breaks the "Go To Comparison" functionality.

I've adjusted the enqueue-ing accordingly.

It still doesn't show the Underline for me though. Either #14 during it got removed, or it is a per-theme problem.

![image](https://cloud.githubusercontent.com/assets/7770631/16465579/83586f68-3e0d-11e6-970e-7a3d27a9b6a5.png)

**Comment by brashrebel** [comment]
Yeah, I think it was Twenty Fifteen specific.

**Comment by d4mation** [comment]
I wasn't even able to see the buttons on Twenty Fifteen (I guess the Actions/Filters don't run properly on the standard Archive template?), but I just added some CSS that should ensure that those buttons don't get a text underline.
