### ISSUE TITLE
Clickable navigation for wide tables

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-compare-products#14]
If a comparison table is wider than the screen, currently it is necessary to side scroll to view whatever is off canvas. However, [this example](https://codyhouse.co/demo/products-comparison-table/index.html) demonstrates a way to enhance that by giving clickable arrows which can be used to scroll through the products.

**Comment by d4mation-** [comment]
I rewrote the Shortcode Output to use an Object Buffer in 82d2224 to make it a bit easier to read, and then hopefully modify to fit a new structure to support clickable arrows like that.

I wanted to go ahead and commit/push that since it is a pretty big change and I didn't want any merge conflicts for anyone else in the near future.

**Comment by d4mation-** [comment]
I've been using the link you gave me as a base in order to figure out something workable. So far it works, but functionality is a bit wonky.

![image](https://cloud.githubusercontent.com/assets/7770631/14540842/1f05f344-0255-11e6-9937-2a7a826e988d.png)

In particular, when you scroll down on that demo it does that neat thing with the first row and fixes it in place and squishes it down. Since it is full-width, it can do that without causing problems. However, when it is within a container like this Shortcode likely will be, it can't hide the fact that when it has `position: fixed` that it is hiding a ton of stuff off to the side of the page (The following is a screenshot from an older commit):

![image](https://cloud.githubusercontent.com/assets/7770631/14541009/ce0a9b60-0255-11e6-8c35-6ea859d0d52d.png)

There doesn't seem to be any way to clip that using any `overflow` rules that I can find. Should we forgo that functionality?

**Comment by brashrebel** [comment]
I'm missing what functionality you mean. The main point of this issue or something more specific?

**Comment by d4mation-** [comment]
A little more specific.

On the demo that you linked to, if you scroll down the top row follows you along the top. However, that only works correctly as it is full-width and is hiding stuff on the right-hand side.

If this is inside a non-full-width container (Which for just about any WordPress site it would be), then the top row will spill off to the right outside of the container when you scroll down unless I disable or somehow rework that feature. I've been unsuccessful in finding a way to clip it so far.

**Comment by brashrebel** [comment]
ah. Ok. That's not critical now. I was only looking at the addition of clickable nav for moving left and right when a table is wide enough to need it. The fixed header row can be a separate issue and will be dealt with later if we even need to.

**Comment by d4mation-** [comment]
Sounds good. Just wanted to run that by you.

Once I figure out how to get the Product Names to fit in there better and get some graphics in there for the Arrow Buttons it will be just about set. I want to clean up the SASS a bit, but that's about all I can think of.

**Comment by d4mation** [comment]
I'd say things are looking pretty good. I've slimmed down the SASS as much as I think I reasonably can and replaced `px` values with `em` values to get things working on the largest amount of devices possible.

![image](https://cloud.githubusercontent.com/assets/7770631/14643245/a85e1c92-061b-11e6-96ba-6825562dda86.png)

Looks good on Mobile as well (Although, by nature, it isn't as useful in Portrait mode)

![image](https://cloud.githubusercontent.com/assets/7770631/14643290/de6f67be-061b-11e6-86d4-8335baff7bd3.png)

It is controlled the same way as before through the backend. I just added `edd_price` repeatedly for testing purposes.

![image](https://cloud.githubusercontent.com/assets/7770631/14643388/351f7ea0-061c-11e6-80d1-734e2070612d.png)

This is a pretty big change (The shortcode was all but entirely rewritten for this), so I figure we may want to test it in some other situations to ensure nothing breaks. I'm using an older dump of Real Big Plugins right now locally.

Can you think of anything that could throw things off? I've got some pretty large titles in there fitting, so that hopefully won't be an issue.

**Comment by d4mation** [comment]
Tracking in #18.
